"""add balance transactions

Revision ID: eb8eef6c0b67
Revises: 913a68af7e62
Create Date: 2026-04-14 10:39:39.786040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8eef6c0b67'
down_revision: Union[str, Sequence[str], None] = '913a68af7e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_transactions_id'), 'balance_transactions', ['id'], unique=False)
    op.add_column('purchases', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('purchases', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('purchases', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('timestamp', sa.DATETIME(), nullable=False))
    op.drop_column('purchases', 'created_at')
    op.drop_column('purchases', 'price')
    op.drop_index(op.f('ix_balance_transactions_id'), table_name='balance_transactions')
    op.drop_table('balance_transactions')
    # ### end Alembic commands ###
